/* The attendee card, in one place.
 *
 * Rendered both by the event site's registration drawer and by the personal
 * invitation pages at /i/{slug}/. The field names below are a contract with
 * attendee() in live-chain.js, which reads them back to build the checkout
 * request, so this template is shared rather than copied: a second copy that
 * drifted would either send details the server rejects or quietly lose a
 * field somebody typed.
 *
 * isMember only changes the label above a card. Everything else is identical
 * for every attendee on every path.
 */
window.ssuiteGuestCard = (i, options) => {
  const isMember = Boolean(options && options.isMember);
  return `<section class="guest-card"><div class="guest-number"><p class="micro">${i===0?'PURCHASER / ATTENDEE':(isMember?'GUEST · COMMUNITY RATE':'ADDITIONAL GUEST')}</p><strong>${i===0?'Your information':`Guest ${i+1}`}</strong></div><div class="form-grid"><label class="field"><span>FIRST NAME</span><input name="guest-${i}-first" autocomplete="given-name" required></label><label class="field"><span>LAST NAME</span><input name="guest-${i}-last" autocomplete="family-name" required></label><label class="field"><span>EMAIL</span><input name="guest-${i}-email" type="email" autocomplete="email" required></label><label class="field"><span>MOBILE PHONE${i===0?'':' <i>OPTIONAL</i>'}</span><input name="guest-${i}-phone" type="tel" autocomplete="tel" maxlength="100"${i===0?' required':''}></label>${i===0?'<p class="sms-note">We may text you about the event — arrival details, or a change on the night. Message and data rates may apply. Reply STOP at any time to stop messages.</p>':''}<label class="field"><span>SECONDARY EMAIL <i>OPTIONAL</i></span><input name="guest-${i}-secondary-email" type="email" placeholder="Assistant or alternate email"></label><label class="field"><span>JOB TITLE</span><input name="guest-${i}-title" required></label><label class="field"><span>COMPANY</span><input name="guest-${i}-company" required></label>${i===0?`<label class="field full-field"><span>HOW DID YOU HEAR ABOUT S.SUITE?</span><select name="referral-source" required><option value="">Select</option><option>SALUTE community</option><option>S.Suite community or event</option><option>Friend or colleague</option><option>Email</option><option>Social media</option><option>Search</option><option>Other</option></select></label>`:''}<label class="field full-field"><span>MEAL PREFERENCE</span><select name="guest-${i}-meal" required><option value="">Select</option><option>Vegetarian</option><option>Non-vegetarian</option></select></label><label class="condition-check full-field"><input type="checkbox" data-detail="dietary-${i}"><span>This guest has allergies or additional dietary needs</span></label><label class="field conditional-field full-field" data-detail-fields="dietary-${i}" hidden><span>ALLERGIES / DIETARY NEEDS</span><input name="guest-${i}-dietary" placeholder="Please be specific"></label><label class="condition-check full-field"><input type="checkbox" data-detail="accessibility-${i}"><span>This guest has accessibility needs</span></label><label class="field conditional-field full-field" data-detail-fields="accessibility-${i}" hidden><span>ACCESSIBILITY NEEDS</span><textarea name="guest-${i}-accessibility" placeholder="Share any accommodations we should prepare."></textarea></label></div></section>`;
};
